<a href="https://colab.research.google.com/github/Akash-12-web/Samsung-Inovation-AIML/blob/main/SIC_ML_Coding_Exercises/SIC_ML_Chapter_03_Coding_Exercises/ex_0204.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Coding Exercise #0204

### 1. Pandas Series:

In [1]:
import pandas as pd
import numpy as np

#### 1.1. Creating Series objects:

In [2]:
my_index = ['a','b','c']
type(my_index)

list

In [3]:
my_index = ['a','b','c']
print("my_index : ", my_index,"\n")

my_values = [222,333,444]
print("my_values : ", my_values,"\n")

my_values2 = (220,330,440)
print("my_values : ", my_values,"\n")

my_dict = {'a':222, 'b':333, 'c':444, 'b':555}
print("my_dict : ", my_dict,"\n")

my_arr = np.array(my_values)
print("my_arr : ", my_arr,"\n")

my_index :  ['a', 'b', 'c']

my_values :  [222, 333, 444]

my_values :  [222, 333, 444]

my_dict :  {'a': 222, 'b': 555, 'c': 444}

my_arr :  [222 333 444]

In [4]:
# Series with list of values
pd.Series(my_values)

0    222
1    333
2    444
dtype: int64

In [5]:
# Series with tuple of values
pd.Series(my_values2)

0    220
1    330
2    440
dtype: int64

In [6]:
# Series with values and index labels.
pd.Series(data=my_values, index=my_index)

a    222
b    333
c    444
dtype: int64

In [7]:
# Series from a NumPy array.
pd.Series(my_arr)

0    222
1    333
2    444
dtype: int64

In [8]:
# Series from a NumPy array with index labels.
pd.Series(my_arr, index=my_index)

a    222
b    333
c    444
dtype: int64

In [9]:
# Series from a dictionary.
x = pd.Series(my_dict)
x

a    222
b    555
c    444
dtype: int64

In [10]:
x.values

array([222, 555, 444])

In [11]:
x.index

Index(['a', 'b', 'c'], dtype='object')

In [12]:
x.values.std()

np.float64(138.44132331063582)

#### 1.2. Series attributes and indexing:

In [13]:
s = pd.Series(data=[111,222,"333",444], index = ['a','b','c','d'], name='MySeries')
print(s)
print(type(s.values[1]))
print(type(s.values[2]))

a    111
b    222
c    333
d    444
Name: MySeries, dtype: object
<class 'int'>
<class 'str'>

Series attributes:

In [14]:
s.index                                   # Index labels.

Index(['a', 'b', 'c', 'd'], dtype='object')

In [15]:
s.name                                    # Name attribute.

'MySeries'

In [16]:
s.dtype                                   # Data type.

dtype('O')

In [17]:
type(s[1])

/tmp/ipykernel_14817/1078778276.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  type(s[1])

int

In [18]:
type(s[2])

/tmp/ipykernel_14817/3417798522.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  type(s[2])

str

In [19]:
"""
    astype(dtype, copy=True, errors='raise')
      copy : Return a copy when copy=True (be very careful setting copy=False as changes to values then may propagate to other pandas objects).
"""
s.astype(float)       # Enables us to set or convert the data type of an existing data column in a dataset or a data frame.

a    111.0
b    222.0
c    333.0
d    444.0
Name: MySeries, dtype: float64

In [20]:
s.values                          # The values as NumPy array.

array([111, 222, '333', 444], dtype=object)

Series indexing and slicing:

In [21]:
s[1]

/tmp/ipykernel_14817/878419959.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[1]

222

In [22]:
s['a']

111

In [23]:
s[2:4]

c    333
d    444
Name: MySeries, dtype: object

In [24]:
s[2:10]       # Be careful that this does not give an error

c    333
d    444
Name: MySeries, dtype: object

In [25]:
print(s[['a','d']])
print(s[['a']])
print(s["a"])
print(s["a":"d"])

print("\n", type(s[['a','d']]))
print(type(s[['a']]))
print(type(s["a"]))
print(type(s["a":"d"]))

a    111
d    444
Name: MySeries, dtype: object
a    111
Name: MySeries, dtype: object
111
a    111
b    222
c    333
d    444
Name: MySeries, dtype: object

 <class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'int'>
<class 'pandas.core.series.Series'>

In [26]:
a = np.arange(9).reshape(3,3)
print(a, "\n")
print("a[0] : ", a[0].shape, "\n", a[0], "\n")
print("a[[0]] : ", a[[0]].shape, "\n", a[[0]],"\n")
print("a[[0,1]] : ", a[[0,1]].shape, "\n", a[[0, 1]], "\n")
print("a[0,1] : ", a[0,1].shape, "\n", a[0,1], "\n")

[[0 1 2]
 [3 4 5]
 [6 7 8]]

a[0] :  (3,)
 [0 1 2]

a[[0]] :  (1, 3)
 [[0 1 2]]

a[[0,1]] :  (2, 3)
 [[0 1 2]
 [3 4 5]]

a[0,1] :  ()
 1

#### 1.3. Series operations:

In [27]:
s1 = pd.Series(data=[1,2,3,4], index = ['d','b','c','a'])
s2 = pd.Series(data=[1,2,3,4], index = ['a','b','d','e'])

print(s1, "\n")
print(s2)

d    1
b    2
c    3
a    4
dtype: int64

a    1
b    2
d    3
e    4
dtype: int64

Please notice that in the Series to Series operations, the elements are matched by the index labels. <br>
When there is no mathing index label, we get **NaN**.

In [28]:
s1 + s2

a    5.0
b    4.0
c    NaN
d    4.0
e    NaN
dtype: float64

In [29]:
s1 - s2

a    3.0
b    0.0
c    NaN
d   -2.0
e    NaN
dtype: float64

In [30]:
s1 * s2

a    4.0
b    4.0
c    NaN
d    3.0
e    NaN
dtype: float64

In [31]:
s1/s2

a    4.000000
b    1.000000
c         NaN
d    0.333333
e         NaN
dtype: float64

In [32]:
2*s1

d    2
b    4
c    6
a    8
dtype: int64

#### 1.4. Series methods:

In [33]:
s1.sum()

np.int64(10)

In [34]:
s1.mean()

np.float64(2.5)

In [35]:
s1.median()

2.5

In [36]:
s1.max()

4

In [37]:
s1.std()

1.2909944487358056

In [38]:
print(s1)
print(s1.sort_values())

d    1
b    2
c    3
a    4
dtype: int64
d    1
b    2
c    3
a    4
dtype: int64

In [39]:
print(s2)
s2.sort_values()

a    1
b    2
d    3
e    4
dtype: int64

a    1
b    2
d    3
e    4
dtype: int64

In [40]:
print(s1)
s1.sort_index()

d    1
b    2
c    3
a    4
dtype: int64

a    4
b    2
c    3
d    1
dtype: int64

In [41]:
print(s1)
s1.sort_values(ascending=False)

d    1
b    2
c    3
a    4
dtype: int64

a    4
c    3
b    2
d    1
dtype: int64

apply() method:

In [42]:
ser_height = pd.Series([165.3, 170.1, 175.0, 182.1, 168.0, 162.0, 155.2, 176.9, 178.5, 176.1, 167.1, 180.0, 162.2, 176.1, 158.2, 168.6, 169.2],
                       name='height')
print(ser_height)

0     165.3
1     170.1
2     175.0
3     182.1
4     168.0
5     162.0
6     155.2
7     176.9
8     178.5
9     176.1
10    167.1
11    180.0
12    162.2
13    176.1
14    158.2
15    168.6
16    169.2
Name: height, dtype: float64

In [43]:
ser_height.apply(lambda x: x/100)     # Convert cm to m

0     1.653
1     1.701
2     1.750
3     1.821
4     1.680
5     1.620
6     1.552
7     1.769
8     1.785
9     1.761
10    1.671
11    1.800
12    1.622
13    1.761
14    1.582
15    1.686
16    1.692
Name: height, dtype: float64

In [44]:
ser_height.nunique()			# Number of unique values in the Series.

16

In [45]:
ser_height.unique()			# Unique values of the Series given as a NumPy array

array([165.3, 170.1, 175. , 182.1, 168. , 162. , 155.2, 176.9, 178.5,
       176.1, 167.1, 180. , 162.2, 158.2, 168.6, 169.2])

In [46]:
ser_height.value_counts()		# Returns a frequency table.

height
176.1    2
165.3    1
175.0    1
170.1    1
168.0    1
162.0    1
155.2    1
182.1    1
176.9    1
178.5    1
167.1    1
180.0    1
162.2    1
158.2    1
168.6    1
169.2    1
Name: count, dtype: int64